Repository 7clickers/ShowRoom3D, pull requests merged in 2022-11, with the labels that each got.

#22 Verbale interno 16 11 2022
  documentazione_interna/verbali/VI_04-11-2022.pdf
  documentazione_interna/verbali/VI_16-11-2022.pdf
  latex/interni/verbali/verbale_interno_04-11-22/VI_04-11-2022.tex
  latex/interni/verbali/verbale_interno_04-11-22/config/changelog_input.tex
  latex/interni/verbali/verbale_interno_04-11-22/config/titlepage_input.tex
  latex/interni/verbali/verbale_interno_04-11-22/config/tracking_input.tex
  latex/interni/verbali/verbale_interno_04-11-22/res/sections/01_introduction.tex
  latex/interni/verbali/verbale_interno_04-11-22/res/sections/02_content.tex
  latex/interni/verbali/verbale_interno_16-11-22/VI_16-11-2022.tex
  latex/interni/verbali/verbale_interno_16-11-22/config/changelog_input.tex
  latex/interni/verbali/verbale_interno_16-11-22/config/titlepage_input.tex
  latex/interni/verbali/verbale_interno_16-11-22/config/tracking_input.tex
  latex/interni/verbali/verbale_interno_16-11-22/res/sections/01_introduction.tex
  latex/interni/verbali/verbale_interno_16-11-22/res/sections/02_content.log
  latex/interni/verbali/verbale_interno_16-11-22/res/sections/02_content.tex
Labels: Da approvare, Da verificare

#21 Norme di progetto
  documentazione_interna/norme_di_progetto.pdf
  latex/interni/doc_interna/norme_di_progetto/config/changelog_input.tex
  latex/interni/doc_interna/norme_di_progetto/config/titlepage_input.tex
  latex/interni/doc_interna/norme_di_progetto/norme_di_progetto.tex
  latex/interni/doc_interna/norme_di_progetto/res/sections/01_content.tex
Labels: P=Media, Da verificare

#31 docs fix VI_16-11-22 tracking_input.tex e aggiornato pdf verbale
  .gitignore
  documentazione_interna/verbali/VI_16-11-2022.pdf
  latex/interni/verbali/verbale_interno_16-11-22/config/tracking_input.tex
Labels: Documentazione, P=Bassa, Da verificare
